#!/usr/bin/env python3
"""
scripts/execute_batch.py — draft execution (v2.5): execution_plan.json → Validated Draft.

The ONLY fill execution in the v2.5 workflow (smoke-test-then-execute is gone:
there is one execution, and its result is kept as the validated draft).

Flow:
  1. Read execution_plan.json (generated by compile_fill.py).
  2. Copy the staged target template → <workdir>/validated_draft<ext>.
  3. Execute the plan's operations in ≤50-op chunks with a coordinate probe
     between chunks.
  4. Machine verification: officecli validate FIRST (flushes edits / forces
     formula evaluation), then issue delta vs the template baseline (templates
     carry their own baseline issues — only NEW issues matter).
  5. Readback every expectation derived by the compiler (values compare
     number-normalized; formulas assert non-empty; nulls assert EMPTY).
  6. Write draft_receipt.json: source/template/spec/plan/draft hashes,
     operation counts, coverage, readback results, issue delta, validation.
  7. The draft is KEPT — the Execution Gate presents it, and the user's
     confirmation promotes it via promote_output.py. Nothing re-executes.

Exit codes: 0=pass (draft validated), 3=retryable (failure record →
fix fill_spec.yaml, recompile, re-run), 1=fatal (env).

Usage:
  python scripts/execute_batch.py --plan <execution_plan.json> \
      --template <staged_target.xlsx> --workdir <dir> [--round N]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _officecli import (  # noqa: E402
    clean_residents, copy_template, ensure_utf8_stdio, fail, issues_delta,
    officecli, officecli_validate, read_cell, record_timing as _record_timing,
    resolve_check_path, sha256_file,
)

CHUNK_SIZE = 50
DRAFT_NAME = "validated_draft"
RECEIPT_NAME = "draft_receipt.json"


FAILURE_NAME = "_draft_failure.json"


def fail_record(workdir: Path, record: dict, exit_code: int) -> None:
    workdir.mkdir(parents=True, exist_ok=True)
    _record_timing(workdir, f"draft_execute_round{record.get('round', '?')}_failed")
    (workdir / FAILURE_NAME).write_text(
        json.dumps(record, ensure_ascii=False, indent=2), encoding="utf-8")
    sys.stderr.write(json.dumps(record, ensure_ascii=False, indent=2))
    sys.exit(exit_code)


TRANSIENT_ERR_RE = re.compile(
    r"file in use|being used by another process|access denied|permission|"
    r"resident|lock|another instance|busy",
    re.IGNORECASE)


def run_batches(book: Path, operations: list, probe_path: str) -> list:
    """Chunked execution with a coordinate probe between chunks.

    officecli batch is atomic per call (a failed call applied nothing), so a
    chunk that fails with a TRANSIENT error (Windows resident/file-lock race
    under parallel load) is retried once after resident cleanup — the observed
    parallel-run flake class (7 retries per run) recovers without agent
    involvement. Real errors (prop rejection, ordering) still stop the run.

    The between-chunk coordinate probe starts a resident; subsequent chunks
    then apply IN MEMORY with the disk write deferred to save/close/idle-
    autosave. Killing that resident (clean_residents taskkill) before the
    deferred flush loses the last chunks' edits — so every batch run ends
    with an explicit `close` (flush + release; no-op without a resident).

    Returns failed chunks: {"chunk_start", "rc", "stdout_tail", "stderr_tail"}."""
    failures = []
    for start in range(0, len(operations), CHUNK_SIZE):
        chunk = operations[start:start + CHUNK_SIZE]
        proc = officecli("batch", str(book), "--commands",
                         json.dumps(chunk, ensure_ascii=False), timeout=600)
        if proc.returncode != 0 and TRANSIENT_ERR_RE.search(proc.stderr or ""):
            # transient infra race: clean residents and retry this chunk once
            clean_residents()
            proc = officecli("batch", str(book), "--commands",
                             json.dumps(chunk, ensure_ascii=False), timeout=600)
            if proc.returncode != 0:
                failures.append({
                    "chunk_start": start, "rc": proc.returncode,
                    "stdout_tail": proc.stdout[-600:], "stderr_tail": proc.stderr[-600:],
                })
                return failures
        elif proc.returncode != 0:
            failures.append({
                "chunk_start": start, "rc": proc.returncode,
                "stdout_tail": proc.stdout[-600:], "stderr_tail": proc.stderr[-600:],
            })
            return failures  # coordinate system may be corrupt — stop at first failure
        if start + CHUNK_SIZE < len(operations) and probe_path \
                and _chunk_has_structural(chunk):
            # Probe only after chunks containing structural ops (add/remove) —
            # pure fill chunks cannot move the coordinate system (2026-08-10:
            # two-block runs dropped ~10 pointless probes).
            probe = officecli("get", str(book), probe_path, "--json")
            if probe.returncode != 0:
                failures.append({
                    "chunk_start": start, "rc": probe.returncode,
                    "stdout_tail": f"coordinate probe failed at {probe_path}",
                    "stderr_tail": probe.stderr[-600:],
                })
                return failures
    # Flush any resident-deferred writes before the caller proceeds (a
    # later clean_residents() taskkill would otherwise drop the tail chunks).
    officecli("close", str(book))
    return failures


def _chunk_has_structural(chunk: list) -> bool:
    return any(op.get("command") in ("add", "remove") for op in chunk)


def number_normalized(value: str) -> float | None:
    """Parse '1,234.50' / '-45.2%' / '$12.00' → float (None when not numeric)."""
    s = value.strip().replace(",", "").replace("%", "")
    s = re.sub(r"[^\d\-+.]", "", s)
    try:
        return float(s)
    except ValueError:
        return None


def _col_idx(letter: str) -> int:
    n = 0
    for ch in letter.upper():
        n = n * 26 + (ord(ch) - ord("A") + 1)
    return n - 1


def _col_letter(idx: int) -> str:
    s = ""
    idx += 1
    while idx > 0:
        idx, rem = divmod(idx - 1, 26)
        s = chr(ord("A") + rem) + s
    return s


def batch_read_cells(book: Path, paths: list[str]) -> dict[str, str]:
    """Read many '/Sheet/A1' cells with ONE range get per sheet.

    Per-cell `officecli get` costs ~0.5s each (179 readbacks ≈ 90s); one
    bounding-box range get returns every cell in ~0.5s total. Non-A1 paths
    (pptx tr/tc, exotic coordinates) are left for per-cell fallback."""
    wanted = set(paths)
    by_sheet: dict[str, list[tuple[int, int, str]]] = {}
    for p in wanted:
        m = re.match(r"^/([^/]+)/([A-Z]+)(\d+)$", p)
        if m:
            by_sheet.setdefault(m.group(1), []).append(
                (_col_idx(m.group(2)), int(m.group(3)), p))
    found: dict[str, str] = {}
    for sheet, cells in by_sheet.items():
        min_c = min(c for c, _, _ in cells)
        max_c = max(c for c, _, _ in cells)
        min_r = min(r for _, r, _ in cells)
        max_r = max(r for _, r, _ in cells)
        rng = f"{_col_letter(min_c)}{min_r}:{_col_letter(max_c)}{max_r}"
        proc = officecli("get", str(book), f"/{sheet}/{rng}", "--depth", "2", "--json")
        if proc.returncode != 0:
            continue
        try:
            data = json.loads(proc.stdout)
            results = data.get("data", {}).get("results", []) or []
            for res in results:
                p = res.get("path", "")
                if p in wanted:
                    found[p] = res.get("text") or ""
                for ch in res.get("children", []) or []:
                    cp = ch.get("path", "")
                    if cp in wanted:
                        found[cp] = ch.get("text") or ""
        except (AttributeError, ValueError):
            continue
    return found


def check_expectation(book: Path, full_path: str, kind: str, expected: str,
                      read_map: dict[str, str] | None = None) -> dict | None:
    """One readback assertion. Returns failure dict or None.

    read_map (from batch_read_cells) supplies actuals; cells missing from the
    map fall back to a single get."""
    if read_map is not None and full_path in read_map:
        actual = read_map[full_path]
    else:
        actual = read_cell(book, full_path)
    if kind == "empty":
        if actual.strip():
            return {"path": full_path, "expected": "EMPTY", "actual": actual, "kind": kind}
        return None
    if kind == "nonempty":
        if not actual.strip():
            return {"path": full_path, "expected": "non-empty", "actual": "", "kind": kind}
        return None
    # value: number-normalized compare, else exact text compare
    exp_num = number_normalized(expected)
    act_num = number_normalized(actual)
    if exp_num is not None and act_num is not None:
        if abs(exp_num - act_num) > 1e-6:
            return {"path": full_path, "expected": expected, "actual": actual, "kind": kind}
        return None
    if actual != expected:
        return {"path": full_path, "expected": expected, "actual": actual, "kind": kind}
    return None


def actual_sheet_rows(book: Path, sheet: str) -> int | None:
    """Read the sheet's final row count via `view outline`. None = unreadable."""
    proc = officecli("view", str(book), "outline", "--json")
    if proc.returncode != 0:
        return None
    try:
        data = json.loads(proc.stdout)
        for s in data.get("data", {}).get("sheets", []):
            if s.get("name") == sheet:
                return int(s.get("rows") or 0)
    except (ValueError, AttributeError, TypeError):
        return None
    return None


def actual_merge_ranges(book: Path, sheet: str, col: str, start_row: int,
                        end_row: int) -> set[str]:
    """Read the col's merged ranges within [start_row, end_row] (format.merge).

    officecli `get` reports the same merge string on the anchor and every
    continuation cell — dedupe. A stale/singleton residue (e.g. A19:A19 after
    row deletion) shows up here; `validate` is blind to it."""
    proc = officecli("get", str(book), f"/{sheet}/{col}{start_row}:{col}{end_row}",
                     "--depth", "1", "--json")
    if proc.returncode != 0:
        return set()
    ranges: set[str] = set()
    try:
        data = json.loads(proc.stdout)
        for res in data.get("data", {}).get("results", []):
            for ch in res.get("children", []):
                m = re.match(rf"^/{re.escape(sheet)}/{col}\d+$", ch.get("path", ""))
                if not m:
                    continue
                mg = (ch.get("format", {}) or {}).get("merge")
                if mg:
                    ranges.add(mg)
    except (ValueError, AttributeError, TypeError):
        return set()
    return ranges


def check_group_boundaries(book: Path, entries: list) -> list:
    """Readback: the actual merged ranges inside each group column's
    data region must EQUAL the compiler-derived expected merges (singletons
    never merge; residue ranges are failures)."""
    failures = []
    for gb in entries or []:
        sheet, col = gb.get("sheet"), gb.get("col")
        r1, r2 = gb.get("region_start"), gb.get("region_end")
        if not (sheet and col and r1 and r2):
            continue
        actual = actual_merge_ranges(book, sheet, col, r1, r2)
        expected = set(gb.get("expected_merges") or [])
        if actual != expected:
            failures.append({
                "sheet": sheet, "col": col, "region": f"{col}{r1}:{col}{r2}",
                "expected_merges": sorted(expected),
                "actual_merges": sorted(actual),
                "code": "GROUP_BOUNDARY_MISMATCH",
            })
    return failures


def render_qa(workdir: Path, draft: Path, region: str, mode: str) -> dict:
    """Capability-aware Render QA. Deterministic QA already ran;
    this renders ONLY the affected region for visual (png) or structural
    (html) inspection. The verdict is the agent's — the script only produces
    the artifact. Single-shot and terminal; failures consume the repair budget."""
    if mode not in ("png", "html"):
        return {"mode": mode, "status": "skipped"}
    ext = "png" if mode == "png" else "html"
    out = workdir / f"render_qa.{ext}"
    cmd = ["view", str(draft), "screenshot" if mode == "png" else "html"]
    if region:
        cmd += ["--range", region]
    cmd += ["-o", str(out)]
    proc = officecli(*cmd, timeout=600)
    if proc.returncode != 0:
        return {"mode": mode, "status": "failed", "region": region,
                "stderr_tail": (proc.stderr or "")[-600:]}
    return {"mode": mode, "status": "produced", "region": region,
            "artifact": str(out)}


def main() -> None:
    ensure_utf8_stdio()
    parser = argparse.ArgumentParser(description="Draft execution: plan → validated draft")
    parser.add_argument("--plan", type=Path, required=True, help="execution_plan.json")
    parser.add_argument("--template", type=Path, required=True,
                        help="staged target template (copied, never modified)")
    parser.add_argument("--workdir", type=Path, required=True)
    parser.add_argument("--round", type=int, default=1, help="repair round (tracking)")
    parser.add_argument("--render", choices=("png", "html", "none"), default="none",
                        help="Render QA: png (multimodal models inspect visually) / "
                             "html (text-only models: structural render check only — "
                             "never claim visual verification) / none (skip)")
    args = parser.parse_args()

    workdir = args.workdir
    workdir.mkdir(parents=True, exist_ok=True)
    clean_residents()

    if not args.plan.is_file():
        fail_record(workdir, {"code": "PLAN_NOT_FOUND",
                              "message": f"plan not found: {args.plan}",
                              "corrective_action": "Run compile_fill.py first"}, 3)
    if not args.template.is_file():
        fail_record(workdir, {"code": "TEMPLATE_NOT_FOUND",
                              "message": f"template not found: {args.template}",
                              "corrective_action": "Stage the target file first"}, 3)

    try:
        plan = json.loads(args.plan.read_text(encoding="utf-8"))
    except ValueError as e:
        fail_record(workdir, {"code": "PLAN_INVALID", "message": str(e),
                              "corrective_action": "Recompile with compile_fill.py"}, 3)

    operations = plan.get("operations")
    if not isinstance(operations, list) or not operations:
        fail_record(workdir, {"code": "PLAN_EMPTY",
                              "message": "plan contains no operations",
                              "corrective_action": "Recompile with compile_fill.py"}, 3)
    platform = plan.get("platform") or \
        ("pptx" if str(args.template).lower().endswith(".pptx") else "xlsx")

    draft_path = workdir / (DRAFT_NAME + args.template.suffix)
    try:
        copy_template(args.template, draft_path)
    except RuntimeError as e:
        fail_record(workdir, {"code": "COPY_FAILED", "message": str(e),
                              "corrective_action": "Check permissions and paths"}, 1)

    # Probe path: first cell-ish path in the operations.
    probe_path = ""
    for op in operations:
        p = op.get("path", "")
        if re.match(r"^/[^/]+/[A-Z]+\d+$", p):
            probe_path = p
            break

    # 1. Execute.
    chunk_failures = run_batches(draft_path, operations, probe_path)
    if chunk_failures:
        from _defect_class import defect_classes, primary_defect, standard_fix
        classes = defect_classes(None, chunk_failures)
        cls = primary_defect(classes)
        fail_record(workdir, {
            "code": "BATCH_CHUNK_FAILED",
            "round": args.round,
            "total_operations": len(operations),
            "failed_chunks": chunk_failures,
            "defect_class": cls, "defect_classes": classes,
            "standard_fix": standard_fix(cls),
            "corrective_action": "Fix fill_spec.yaml per standard_fix, recompile, re-run",
        }, 3)

    # 2. Machine verification: validate FIRST, then issue delta vs template.
    #    A template that itself fails `officecli validate` (e.g. pptx chart
    #    schema extensions) makes validate non-discriminating — same spirit as
    #    the issue delta: only NEW defects matter. validate_ok becomes
    #    "template-baseline" (recorded, non-blocking) in that case.
    validate_ok = officecli_validate(draft_path)
    validate_state = "ok" if validate_ok else "fail"
    if not validate_ok:
        template_validate_ok = officecli_validate(args.template)
        if not template_validate_ok:
            validate_state = "template-baseline"
            print(f"[EXECUTE_BATCH] INFO — template itself fails `officecli validate`; "
                  f"validate treated as baseline noise (issue delta remains the gate)",
                  file=sys.stderr)
    issues_supported, issue_count, new_issues = issues_delta(draft_path, args.template)
    if not issues_supported:
        print(f"[EXECUTE_BATCH] INFO — `view issues` mode unavailable; "
              f"structural check uses validate only", file=sys.stderr)

    # 3. Readback from compiler-derived expectations (no hand-written checks).
    #    One range get per sheet, then evaluate each expectation.
    readback_paths = [rb["path"] for rb in plan.get("readback", [])]
    read_map = batch_read_cells(draft_path, readback_paths)
    check_failures = []
    for rb in plan.get("readback", []):
        full_path = resolve_check_path(operations, rb["path"])
        failure = check_expectation(draft_path, full_path, rb.get("kind", "value"),
                                    rb.get("expect", ""), read_map)
        if failure:
            check_failures.append(failure)

    # 3b. Structural readback: final row count + group boundary
    #     assertions. officecli `validate` is blind to merge residue; the
    #     compiler-derived group boundaries are the only closed check.
    structural = {"expected_final_row_count": None, "actual_final_row_count": None,
                  "pass": True, "failures": []}
    if platform == "xlsx":
        expected_rows = plan.get("expected_final_row_count")
        if expected_rows:
            actual_rows = actual_sheet_rows(draft_path, plan.get("target_sheet", ""))
            structural["expected_final_row_count"] = expected_rows
            structural["actual_final_row_count"] = actual_rows
            if actual_rows is None:
                structural["pass"] = False
                structural["failures"].append({
                    "code": "FINAL_ROW_COUNT_MISMATCH",
                    "expected": expected_rows, "actual": None,
                    "message": "could not read the draft's sheet row count",
                })
            elif actual_rows != expected_rows:
                structural["pass"] = False
                structural["failures"].append({
                    "code": "FINAL_ROW_COUNT_MISMATCH",
                    "expected": expected_rows, "actual": actual_rows,
                })
        group_failures = check_group_boundaries(draft_path,
                                                plan.get("group_boundaries", []))
        if group_failures:
            structural["pass"] = False
            structural["failures"].extend(group_failures)

    # 4. Source coverage (per-source entries in multi-source plans).
    coverage = plan.get("source_coverage", [])
    if isinstance(coverage, dict):
        coverage = [coverage]
    coverage_result = "pass"
    if any(c.get("required_unmatched") for c in coverage):
        coverage_result = "fail"

    if (issue_count not in (None, 0)) or validate_state == "fail" or check_failures \
            or coverage_result != "pass" or not structural["pass"]:
        from _defect_class import defect_classes, primary_defect, standard_fix
        classes = defect_classes(new_issues, chunk_failures,
                                 structural.get("failures"))
        cls = primary_defect(classes)
        fail_record(workdir, {
            "code": "DRAFT_VERIFY_FAILED",
            "round": args.round,
            "issues_count": issue_count,
            "new_issues": sorted(f"{p} [{s}]" for p, s, m in (new_issues or set())),
            "validate_state": validate_state,
            "readback_failures": check_failures,
            "structural_failures": structural["failures"],
            "source_coverage": coverage_result,
            "defect_class": cls, "defect_classes": classes,
            "standard_fix": standard_fix(cls),
            "corrective_action": "修复是预期步骤: 按 standard_fix 修 fill_spec.yaml, "
                                 "重编译, 重执行 — 不询问用户; 连续第 2 次失败才分类为 "
                                 "ASK/STOP",
        }, 3)

    # 5. Render QA (Q13): capability-aware, single-shot, terminal. The artifact
    #    is produced here; the visual/structural verdict is the agent's.
    render_result = render_qa(workdir, draft_path,
                              (plan.get("render_qa") or {}).get("region", ""),
                              args.render)
    if render_result.get("status") == "failed":
        fail_record(workdir, {
            "code": "RENDER_QA_FAILED",
            "round": args.round,
            "render": render_result,
            "corrective_action": "修复是预期步骤: 降级 --render html, 或按 spec 修复后"
                                 "重跑 — 不询问用户; 连续第 2 次失败才分类为 ASK/STOP",
        }, 3)

    officecli("close", str(draft_path))  # flush any resident-deferred edits to disk
    clean_residents()

    receipt = {
        "schema_version": "2.5",
        "round": args.round,
        "source_hashes": _source_hashes(args.workdir, plan),
        "template_sha256": sha256_file(args.template),
        "fill_spec_sha256": plan.get("fill_spec_sha256"),
        "execution_plan_sha256": sha256_file(args.plan),
        "draft_sha256": sha256_file(draft_path),
        "draft_path": str(draft_path),
        "operation_counts": _op_counts(operations),
        "source_coverage": {"entries": coverage, "result": coverage_result},
        "readback": {"total": len(plan.get("readback", [])),
                     "passed": len(plan.get("readback", [])) - len(check_failures)},
        "structural": structural,
        "render_qa": render_result,
        "issue_delta": {"supported": issues_supported, "new_issues": issue_count},
        "validate": validate_state,
        "key_outputs": plan.get("key_outputs", []),
    }
    _record_timing(workdir, "draft_execute")
    (workdir / RECEIPT_NAME).write_text(
        json.dumps(receipt, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps({
        "status": "PASS", "code": "DRAFT_VALIDATED",
        "round": args.round,
        "operations": len(operations),
        "issues_new": issue_count,
        "validate_state": validate_state,
        "readback": receipt["readback"],
        "structural": {"pass": structural["pass"],
                       "final_row_count": structural["actual_final_row_count"]},
        "render_qa": render_result.get("status"),
        "coverage": coverage_result,
        "draft": str(draft_path),
        "draft_sha256": receipt["draft_sha256"],
        "receipt": str(workdir / RECEIPT_NAME),
    }, ensure_ascii=False, indent=2))
    sys.exit(0)


def _source_hashes(workdir: Path, plan: dict) -> dict:
    import hashlib
    out = {}
    manifest = workdir / "prepare_manifest.json"
    if manifest.is_file():
        try:
            m = json.loads(manifest.read_text(encoding="utf-8"))
            for f in m.get("files", []):
                out[f["staged"]] = f.get("sha256")
        except ValueError:
            pass
    return out


def _op_counts(operations: list) -> dict:
    counts = {}
    for op in operations:
        c = op.get("command", "?")
        kind = "set"
        if c == "add":
            kind = "add"
        elif c == "remove":
            kind = "remove"
        elif "merge" in op.get("props", {}):
            kind = "merge"
        elif "formula" in op.get("props", {}):
            kind = "formula"
        elif "value" in op.get("props", {}):
            kind = "value" if op.get("props", {}).get("value") is not None else "null"
        counts[kind] = counts.get(kind, 0) + 1
    return counts


if __name__ == "__main__":
    main()
