"""Ticket 02 (P0-02) — Hierarchical Matrix Canonical Regression: full-chain E2E.

Replays the REAL hierarchical parameter-sheet shape through the whole Runtime
seam — Prepare (real officecli flatten with merged-parent propagation) → Matrix
FillSpec (all three locator forms mixed) → Compile → Execute → Structural Gate
(draft_receipt) → Semantic Gate (final workbook scan) — plus the negative
regression that locks "first match wins" can never come back.

Fixture: tests/_fixtures/hierarchical_matrix/ (data-neutral canonical asset,
checked-in xlsx generated by the dev-time generate_fixtures.py — the test
COPIES the checked-in workbooks into a temp workdir and NEVER imports the
generator). Structure (see the generator docstring):

  source_parameter_book.xlsx (sheet Params, internal-facing):
    - A = Section with REAL vertical merges (Cooling A3:A6, Heating A7:A9) —
      flatten propagates the anchor into every child row's A cell;
    - B = Parameter (duplicated: Capacity ×3, EER/Operation/COP/Sound/Supply);
    - C = Unit — the final disambiguator (Btu/h vs W);
    - D/E/F = records (12K/18K/24K tokens), data-neutral values;
    - Operation row carries the sanctioned controlled source value
      "Heating pump" → target "Cooling and Heating" (spec D9 example variant —
      see generator docstring for why the controlled vocabulary is ASCII);
    - Supply row carries padded " 220 " values → trim → "220";
    - Internal | Cost Code | USD | 内部成本×3 = internal-only row: present in
      the source, absent in the target, unmapped by field_map — must never
      reach the final workbook.

  target_template.xlsx (sheet Template, customer-facing): same field rows
  minus the internal row (rows offset by +1 due to the note row — locators
  must not depend on absolute row equality between sides).

Hard acceptance (all must hold simultaneously):
  - Matrix compile PASS (exit 0, no defects);
  - A/B/C target schema writes = 0 (every plan write column ⊆ {D,E,F});
  - 100% source lineage: |source_trace| == |writes|, write paths == trace
    paths, every entry exactly {target, source, transform_chain};
  - zero BULK_SOURCE_DERIVED_LITERAL_FALLBACK warning; zero
    MATRIX_FIELD_LOCATOR_AMBIGUOUS;
  - Structural Gate PASS (draft_receipt.json) AND Semantic Gate PASS (exit 0);
  - internal-only values absent from the final workbook (zip/XML scan);
  - data-neutrality self-check (forbidden tokens absent from fixtures, flat
    CSVs, produced JSON and the final workbook).

Negative regression: the same fixture with a bad spec — field_map contains
ONLY the legacy string locator `source: Capacity` / `target: Capacity` with
`field_label_column: B` declared on both sides (Capacity lives in column B and
appears 3×) → compile MUST FAIL, exit 3, FIRST defect code
MATRIX_FIELD_LOCATOR_AMBIGUOUS, and MATRIX_FIELD_LOCATOR_NOT_FOUND must NOT be
present. Asserted via the CLI (authoritative) and in-process (compile_spec).

Known environment fact (KNOWN_TRAPS · Office concurrency and officecli 1.0.145
mechanics): officecli batch can transiently fail (~1/4 BATCH_CHUNK_FAILED) and
its get/batch JSON returns non-ASCII as XML numeric character references; the
execute step is retried ONCE on BATCH_CHUNK_FAILED (documented product recovery
path), and the controlled vocabulary is ASCII by design (see the generator).

Run:
  python -m pytest table-fill/tests/test_matrix_hierarchical_regression.py -q
"""

from __future__ import annotations

import csv
import hashlib
import html as _html
import json
import shutil
import subprocess
import sys
import tempfile
import time
import unittest
import zipfile
from pathlib import Path

import yaml

SKILL_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = SKILL_ROOT / "scripts"
FIX = Path(__file__).resolve().parent / "_fixtures" / "hierarchical_matrix"
SRC_XLSX = FIX / "source_parameter_book.xlsx"
TGT_XLSX = FIX / "target_template.xlsx"
SEM_FIX = Path(__file__).resolve().parent / "_fixtures" / "semantic_gate"
MODS_FIX = SEM_FIX / "MODS_param"
MOD_MD = MODS_FIX / "MOD_param.md"

SRC_FILE = "source_parameter_book.xlsx"
TGT_FILE = "target_template.xlsx"
SRC_ENTRY = "source_parameter_book_Params"
TGT_ENTRY = "target_template_Template"
SRC_SHEET = "Params"
TGT_SHEET = "Template"

# 8 mapped fields × 3 record columns = 24 matrix writes (Internal excluded).
N_FIELDS = 8
N_RECORDS = 3
N_WRITES = N_FIELDS * N_RECORDS

# Contract (data-neutral): (target row, target col, expected materialized
# value). Derived from the fixture contract — the same values a reader of the
# source flat CSV expects after transform chains:
#   Cooling/Capacity/Btu/h (tgt 4) direct; Cooling/Capacity/W (tgt 5) guarded;
#   Cooling/EER (tgt 6); Cooling/Operation (tgt 7) [op_translate];
#   Heating/Capacity (tgt 8); Heating/COP (tgt 9); Heating/Sound (tgt 10);
#   Voltage/Supply (tgt 11) [trim].
EXPECTED_WRITES = {
    (4, "D"): "12000",      (4, "E"): "18000",      (4, "F"): "24000",
    (5, "D"): "3500",       (5, "E"): "5300",       (5, "F"): "7000",
    (6, "D"): "11",         (6, "E"): "10.8",       (6, "F"): "11.6",
    (7, "D"): "Cooling and Heating", (7, "E"): "Cooling and Heating",
    (7, "F"): "Cooling and Heating",
    (8, "D"): "14000",      (8, "E"): "21000",      (8, "F"): "28000",
    (9, "D"): "3.6",        (9, "E"): "3.8",        (9, "F"): "4",
    (10, "D"): "42",        (10, "E"): "45",        (10, "F"): "48",
    (11, "D"): "220",       (11, "E"): "220",       (11, "F"): "220",
}

FORBIDDEN_TOKENS = ["埃及", "Egypt", "TCL", "MXP", "ATLAS", "Algeria", "Z2U"]


def run_py(workdir: Path, script: str, *args) -> subprocess.CompletedProcess:
    """Suite e2e subprocess seam (cwd=workdir, Office-stage timeout 900)."""
    return subprocess.run(
        [sys.executable, "-X", "utf8", str(SCRIPTS / script), *args],
        cwd=str(workdir), capture_output=True, text=True, encoding="utf-8",
        errors="replace", timeout=900)


def load_flat_rows(workdir: Path, name: str) -> list[tuple[list[str], int]]:
    """Read a flattened CSV (utf-8-sig) into [(values, orig_row), ...]."""
    rows = []
    with open(workdir / f"{name}_flat.csv", encoding="utf-8-sig",
              newline="") as fh:
        for line in csv.reader(fh):
            if not line:
                continue
            try:
                orig = int(line[-1].strip())
            except (ValueError, IndexError):
                continue
            rows.append((line[:-1], orig))
    return rows


def zip_text(path: Path) -> str:
    """Every zip part of a workbook, XML-entity-unescaped (catches both raw
    and escaped leakage — officecli stores non-ASCII as numeric char refs)."""
    with zipfile.ZipFile(path) as z:
        return _html.unescape("".join(
            z.read(n).decode("utf-8", errors="replace")
            for n in z.namelist()))


def file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def mod_record(mods_copy: Path) -> dict:
    """MOD Adjudication Record locked to the param_sheet MOD (canonical
    path/revision/sha256) — consumed by BOTH compile (C1–C3) and the semantic
    gate (canonical resolver)."""
    sha = file_sha256(mods_copy / "MOD_param.md")
    return {
        "status": "resolved", "selected": "param_sheet",
        "selected_revision": 1,
        "selected_canonical_path": "MOD_param.md",
        "selected_sha256": sha,
        "candidates": [{"name": "param_sheet",
                        "canonical_path": "MOD_param.md",
                        "revision": 1, "sha256": sha}],
    }


def build_spec(manifest: dict, guarded: tuple[int, int]) -> dict:
    """The canonical hierarchical-matrix FillSpec: ALL THREE locator forms
    mixed — 5 composite matches, 1 guarded explicit row (orig numbers verified
    from the flattened CSVs after prepare), 1 legacy unique label (Supply,
    unique in column B), plus the Operation field via composite + transform.
    field_label_column: B (the parameter column) on both sides."""
    src_guard, tgt_guard = guarded
    fm = [
        {"source": {"match": {"A": "Cooling", "B": "Capacity", "C": "Btu/h"}},
         "target": {"match": {"A": "Cooling", "B": "Capacity", "C": "Btu/h"}}},
        {"source": {"row": src_guard,
                    "expect": {"A": "Cooling", "B": "Capacity", "C": "W"}},
         "target": {"row": tgt_guard,
                    "expect": {"A": "Cooling", "B": "Capacity", "C": "W"}}},
        {"source": {"match": {"A": "Cooling", "B": "EER", "C": "Btu/Wh"}},
         "target": {"match": {"A": "Cooling", "B": "EER", "C": "Btu/Wh"}}},
        {"source": {"match": {"A": "Cooling", "B": "Operation", "C": "Mode"}},
         "target": {"match": {"A": "Cooling", "B": "Operation", "C": "Mode"}},
         "transforms": ["op_translate"]},
        {"source": {"match": {"A": "Heating", "B": "Capacity", "C": "Btu/h"}},
         "target": {"match": {"A": "Heating", "B": "Capacity", "C": "Btu/h"}}},
        {"source": {"match": {"A": "Heating", "B": "COP", "C": "W/W"}},
         "target": {"match": {"A": "Heating", "B": "COP", "C": "W/W"}}},
        {"source": {"match": {"A": "Heating", "B": "Sound", "C": "dB(A)"}},
         "target": {"match": {"A": "Heating", "B": "Sound", "C": "dB(A)"}}},
        {"source": "Supply", "target": "Supply", "transforms": ["trim"]},
    ]
    fp = manifest["fingerprints"]
    return {
        "task": {"intent": "Hierarchical matrix canonical regression (P0-02): "
                 "parameter sheet → matrix fill with composite/guarded/legacy "
                 "locators, controlled translation and trim",
                 "selected_mod": "param_sheet", "selected_mod_revision": 1},
        "inputs": {"sources": [SRC_FILE], "target": TGT_FILE,
                   "source_sheets": [{"source": SRC_FILE,
                                      "sheets": [SRC_SHEET]}],
                   "target_sheet": TGT_SHEET},
        "fingerprints": {"source_structure": fp["source_structure"],
                         "target_structure": fp["target_structure"]},
        "mapping": {
            "transforms": [
                {"name": "op_translate", "function": "controlled_translation",
                 "translations": {"Heating pump": "Cooling and Heating"}},
            ],
            "targets": [{
                "sheet": TGT_SHEET,
                "matrix": {
                    "source": {"flatten": SRC_ENTRY, "field_axis": "rows",
                               "record_axis": "columns",
                               "field_label_column": "B"},
                    "target": {"field_axis": "rows", "record_axis": "columns",
                               "field_label_column": "B"},
                    "field_map": fm,
                    "record_map": [
                        {"record": "12K", "source_column": "D",
                         "target_column": "D"},
                        {"record": "18K", "source_column": "E",
                         "target_column": "E"},
                        {"record": "24K", "source_column": "F",
                         "target_column": "F"},
                    ],
                },
            }],
        },
        "decisions": ["internal-only 行 (Internal/Cost Code/USD) 不映射 —— "
                      "field_map 决定外发字段，非全表复制; 受控翻译 "
                      "Heating pump→Cooling and Heating (spec 许可英文示例)"],
        "gaps": [],
        "lineage": [{"source": f"{SRC_ENTRY}_flat.csv", "role": "primary",
                     "note": "matrix hierarchical field locator (composite + "
                             "guarded + legacy) × record_map"}],
        "validation": {"required_coverage": [], "required_empty": [],
                       "key_outputs": ["D4", "E5", "F7", "F11"]},
    }


def build_negative_spec(manifest: dict) -> dict:
    """The negative regression spec: ONLY the legacy string locator
    `Capacity` (duplicated 3× in column B) with field_label_column: B on both
    sides — must fail AMBIGUOUS, never first-match."""
    spec = build_spec(manifest, (4, 5))
    spec["task"]["intent"] = "negative: duplicated legacy label must fail"
    spec["mapping"]["targets"][0]["matrix"]["field_map"] = [
        {"source": "Capacity", "target": "Capacity"}]
    spec["validation"]["key_outputs"] = []
    return spec


def semantic_policy() -> dict:
    """Executable translation of the param_sheet MOD's validation rules
    (SEC-003 / SEC-001 / ID-001 / TRN-001 / FLD-004 / VAL-002) over the filled
    record region Template!D4:F11 (the 24 matrix cells)."""
    return {"checks": [
        {"check": "cjk_leakage", "rule_id": "SEC-003",
         "range": f"{TGT_SHEET}!D4:F11"},
        {"check": "internal_only", "rule_id": "SEC-001",
         "range": f"{TGT_SHEET}!D4:F11",
         "terms": ["Internal", "Cost Code", "内部成本", "研发", "原型"]},
        {"check": "whitespace", "rule_id": "ID-001",
         "range": f"{TGT_SHEET}!D4:F11"},
        {"check": "controlled_translation", "rule_id": "TRN-001",
         "range": f"{TGT_SHEET}!D4:F11",
         "allowed": ["Cooling and Heating", "wide fin"],
         "forbidden": ["宽片", "Heating pump", "Heat Pump"],
         "translations": [{"from": "Heating pump", "to": "Cooling and Heating"}],
         "controlled_translation_transforms": ["op_translate"]},
        {"check": "template_stale", "rule_id": "FLD-004",
         "range": f"{TGT_SHEET}!D4:F11", "stale_values": ["placeholder", "TBD"]},
        {"check": "unresolved_placeholder", "rule_id": "FLD-004",
         "range": f"{TGT_SHEET}!D4:F11"},
        {"check": "source_lineage", "rule_id": "VAL-002",
         "range": f"{TGT_SHEET}!D4:F11"},
    ]}


@unittest.skipIf(shutil.which("officecli") is None, "officecli not on PATH")
class HierarchicalMatrixRegressionTests(unittest.TestCase):
    """The ticket's hard acceptance, driven entirely through the public CLIs."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="hmx_reg_")
        self.workdir = Path(self._tmp.name)
        self.mods = self.workdir / "MODS_param"
        shutil.copytree(MODS_FIX, self.mods)
        shutil.copy2(SRC_XLSX, self.workdir / SRC_FILE)
        shutil.copy2(TGT_XLSX, self.workdir / TGT_FILE)

    def tearDown(self):
        sys.path.insert(0, str(SCRIPTS))
        from _officecli import clean_residents, unlink_retry  # noqa: PLC0415
        clean_residents()          # release officecli file locks
        time.sleep(1.0)            # Windows releases handles asynchronously
        for p in sorted(self.workdir.rglob("*"), reverse=True):
            try:
                if p.is_file():
                    unlink_retry(p)
                else:
                    p.rmdir()
            except OSError:
                pass
        self._tmp.cleanup()

    def _prepare(self):
        """Stage + outline + flatten (real officecli flatten)."""
        proc = run_py(self.workdir, "prepare_run.py", "--workdir", ".",
                      "--files",
                      f"{SRC_FILE}|{SRC_FILE},{TGT_FILE}|{TGT_FILE}", "--outline")
        self.assertEqual(proc.returncode, 0, proc.stderr[-800:])
        proc = run_py(self.workdir, "prepare_run.py", "--workdir", ".",
                      "--flatten",
                      "--sheets", f"{SRC_FILE}:{SRC_SHEET};{TGT_FILE}:{TGT_SHEET}",
                      "--target", TGT_FILE)
        self.assertEqual(proc.returncode, 0, proc.stderr[-800:])
        return json.loads(
            (self.workdir / "prepare_manifest.json").read_text(encoding="utf-8"))

    def _verify_flat_contract(self, manifest) -> tuple[int, int]:
        """Assert the flatten contract (merged-parent propagation into A for
        every child row; internal row only in the source) and return the
        guarded-row orig numbers (source/target Cooling/Capacity/W) which the
        spec's guarded locators must use — verified here, after prepare."""
        src = load_flat_rows(self.workdir, SRC_ENTRY)
        tgt = load_flat_rows(self.workdir, TGT_ENTRY)
        by_orig_src = {orig: vals for vals, orig in src}
        by_orig_tgt = {orig: vals for vals, orig in tgt}
        # merged parents propagated into every child row's A cell
        for orig in (3, 4, 5, 6):
            self.assertEqual(by_orig_src[orig][0], "Cooling",
                             f"source orig {orig} A must be 'Cooling'")
        for orig in (7, 8, 9):
            self.assertEqual(by_orig_src[orig][0], "Heating",
                             f"source orig {orig} A must be 'Heating'")
        for orig in (4, 5, 6, 7):
            self.assertEqual(by_orig_tgt[orig][0], "Cooling",
                             f"target orig {orig} A must be 'Cooling'")
        for orig in (8, 9, 10):
            self.assertEqual(by_orig_tgt[orig][0], "Heating",
                             f"target orig {orig} A must be 'Heating'")
        # B duplicated (the fail-closed trigger for the negative regression)
        b_src = [v[1] for v in by_orig_src.values()]
        self.assertEqual(b_src.count("Capacity"), 3)
        # unit is the final disambiguator in the source AND the target
        for _, vals in by_orig_src.items():
            if vals[1] == "Capacity":
                self.assertIn(vals[2], ("Btu/h", "W"))
        # internal-only row exists ONLY in the source
        internal_src = [v for v in by_orig_src.values() if v[1] == "Cost Code"]
        self.assertEqual(len(internal_src), 1)
        self.assertEqual(internal_src[0][0], "Internal")
        self.assertEqual(internal_src[0][2], "USD")
        # officecli 1.0.145 flattens non-ASCII as XML numeric char refs —
        # unescape before comparing with the raw token
        self.assertIn("内部成本", _html.unescape(internal_src[0][3]))
        self.assertFalse(any(v[1] == "Cost Code" for v in by_orig_tgt.values()),
                         "target must NOT carry the internal-only row")
        # guarded origins: Cooling/Capacity/W (source orig 4, target orig 5)
        src_guard = next(orig for vals, orig in src
                         if vals[1] == "Capacity" and vals[2] == "W")
        tgt_guard = next(orig for vals, orig in tgt
                         if vals[1] == "Capacity" and vals[2] == "W")
        self.assertEqual(src_guard, 4)
        self.assertEqual(tgt_guard, 5)
        self.assertNotEqual(src_guard, tgt_guard,
                            "source/target row numbers deliberately differ "
                            "(locators must not depend on absolute order)")
        return src_guard, tgt_guard

    def test_full_chain_e2e_and_hard_acceptance(self):
        wd = self.workdir
        manifest = self._prepare()
        src_guard, tgt_guard = self._verify_flat_contract(manifest)

        # MOD lock (compile C1–C3 + semantic gate share this record)
        (wd / "mod_resolution.json").write_text(
            json.dumps(mod_record(self.mods), ensure_ascii=False),
            encoding="utf-8")

        # ── 2. Matrix FillSpec (real matrix, all three locator forms) ──
        spec = build_spec(manifest, (src_guard, tgt_guard))
        (wd / "fill_spec.yaml").write_text(
            yaml.safe_dump(spec, allow_unicode=True, sort_keys=False),
            encoding="utf-8")

        # ── 3. Compile (public CLI) ──
        proc = run_py(wd, "compile_fill.py", "--spec", "fill_spec.yaml",
                      "--workdir", ".")
        self.assertEqual(proc.returncode, 0,
                         proc.stdout[-800:] + proc.stderr[-1500:])
        plan = json.loads((wd / "execution_plan.json").read_text(encoding="utf-8"))

        # Matrix compile PASS + zero AMBIGUOUS + zero bulk literal fallback
        self.assertIsNotNone(plan["matrix"])
        self.assertEqual(plan["matrix"]["source"], SRC_ENTRY)
        warn_codes = {w.get("code") for w in plan["warnings"]}
        self.assertNotIn("BULK_SOURCE_DERIVED_LITERAL_FALLBACK", warn_codes)
        self.assertNotIn("MATRIX_FIELD_LOCATOR_AMBIGUOUS", warn_codes)

        # A/B/C target schema writes = 0; writes ⊆ {D,E,F}
        self.assertEqual(len(plan["writes"]), N_WRITES)
        self.assertTrue(all(w["col"] in {"D", "E", "F"} for w in plan["writes"]),
                        f"A/B/C schema columns leaked into writes: "
                        f"{[w for w in plan['writes'] if w['col'] not in ('D','E','F')]}")
        self.assertEqual(plan["sets"], [], "no literal sets (schema columns stay 0)")

        # 100% source lineage: |trace| == |writes| and paths coincide
        self.assertEqual(len(plan["source_trace"]), N_WRITES)
        trace_paths = {t["target"] for t in plan["source_trace"]}
        write_paths = {f"/{TGT_SHEET}/{w['col']}{w['row']}"
                       for w in plan["writes"]}
        self.assertEqual(trace_paths, write_paths)
        for entry in plan["source_trace"]:
            self.assertEqual(set(entry.keys()),
                             {"target", "source", "transform_chain"})

        # materialized values match the contract (translate + trim + direct)
        got = {(w["row"], w["col"]): w["value"] for w in plan["writes"]}
        self.assertEqual(got, EXPECTED_WRITES)
        # transform chains land in lineage (composite + guarded + legacy)
        chain = {t["target"]: t["transform_chain"]
                 for t in plan["source_trace"]}
        self.assertEqual(chain[f"/{TGT_SHEET}/D7"], ["op_translate"])
        self.assertEqual(chain[f"/{TGT_SHEET}/D11"], ["trim"])
        self.assertEqual(chain[f"/{TGT_SHEET}/D5"],
                         [], "guarded row: direct copy")
        source_trace = json.loads(
            (wd / "source_trace.json").read_text(encoding="utf-8"))
        self.assertEqual(source_trace, plan["source_trace"])
        # key outputs sampled from the plan's own written set
        self.assertEqual({ko["path"] for ko in plan["key_outputs"]},
                         {f"/{TGT_SHEET}/D4", f"/{TGT_SHEET}/E5",
                          f"/{TGT_SHEET}/F7", f"/{TGT_SHEET}/F11"})

        # ── 4. Execute (structural gate) — retry ONCE on the documented
        #    transient officecli batch flake (KNOWN_TRAPS ~1/4
        #    BATCH_CHUNK_FAILED under resident concurrency) ──
        proc = run_py(wd, "execute_batch.py", "--plan", "execution_plan.json",
                      "--template", TGT_FILE, "--workdir", ".",
                      "--round", "1", "--render", "html")
        if proc.returncode != 0:
            failure = json.loads(
                (wd / "_draft_failure.json").read_text(encoding="utf-8"))
            self.assertEqual(
                failure["code"], "BATCH_CHUNK_FAILED",
                "non-transient execute failure (must not be silently retried): "
                f"{proc.stdout[-600:]} {proc.stderr[-600:]}")
            proc = run_py(wd, "execute_batch.py", "--plan", "execution_plan.json",
                          "--template", TGT_FILE, "--workdir", ".",
                          "--round", "2", "--render", "html")
        self.assertEqual(proc.returncode, 0,
                         proc.stdout[-800:] + proc.stderr[-1500:])
        receipt = json.loads((wd / "draft_receipt.json").read_text(encoding="utf-8"))
        self.assertTrue(receipt["structural"]["pass"])
        self.assertEqual(receipt["readback"]["passed"], receipt["readback"]["total"])
        self.assertEqual(receipt["readback"]["total"], N_WRITES)
        self.assertEqual(receipt["issue_delta"]["new_issues"], 0)
        self.assertEqual(receipt["validate"], "ok")
        self.assertEqual(receipt["render_qa"]["status"], "produced")
        self.assertTrue((wd / "validated_draft.xlsx").is_file())
        draft = wd / "validated_draft.xlsx"

        # ── 5. Semantic Gate (final workbook scan, MOD rule_ids) ──
        (wd / "semantic_policy.json").write_text(
            json.dumps(semantic_policy(), ensure_ascii=False), encoding="utf-8")
        proc = run_py(wd, "semantic_gate.py", "--workdir", ".",
                      "--mods-dir", str(self.mods))
        self.assertEqual(proc.returncode, 0,
                         f"semantic gate: {proc.stdout[-800:]} {proc.stderr[-800:]}")
        srec = json.loads((wd / "semantic_receipt.json").read_text(encoding="utf-8"))
        self.assertEqual(srec["status"], "PASS")
        self.assertEqual(srec["violations_total"], 0)
        self.assertEqual(srec["mod"]["name"], "param_sheet")
        self.assertTrue(srec["scanned_file_sha256"])
        by_check = {c["check"]: c for c in srec["checks"]}
        for c in srec["checks"]:
            self.assertEqual(c["cell_count"], N_WRITES, c["check"])
            self.assertEqual(c["violations"], 0, c["check"])
            self.assertIn(c["rule_id"],
                          {"SEC-001", "SEC-003", "ID-001", "TRN-001",
                           "FLD-004", "VAL-002"})
        ctrl = by_check["controlled_translation"]
        comp = {e["cell"]: e for e in ctrl["compliant_cells"]}
        for ref in ("D7", "E7", "F7"):
            self.assertEqual(comp[f"{TGT_SHEET}!{ref}"]["value"],
                             "Cooling and Heating")
            self.assertIn("controlled_translation_lineage",
                          comp[f"{TGT_SHEET}!{ref}"]["basis"])

        # ── 6. Hard acceptance: internal-only values ABSENT from the final
        #    workbook (zip/XML scan — the check object is the file on disk) ──
        draft_text = zip_text(draft)
        for token in ("Internal", "Cost Code", "USD", "内部成本"):
            self.assertNotIn(token, draft_text,
                             f"internal-only token {token!r} leaked into the "
                             "final workbook")
        # positive control: the scan sees the real filled content
        for token in ("Cooling", "Heating", "Supply", "Cooling and Heating"):
            self.assertIn(token, draft_text,
                          f"filled content {token!r} missing from the draft")

        # ── 7. Data-neutrality self-check ──
        self._data_neutrality(draft, manifest)

    def _data_neutrality(self, draft: Path, manifest: dict) -> None:
        """Forbidden real-customer tokens must never appear in the checked-in
        fixtures, the flattened CSVs, the produced JSON/MD or the final
        workbook (raw or entity-escaped)."""
        texts = []
        for path in (SRC_XLSX, TGT_XLSX, draft):
            texts.append((path.name, zip_text(path)))
        for p in sorted(self.workdir.glob("*.csv")):
            texts.append((p.name, p.read_text(encoding="utf-8-sig")))
        for name in ("fill_spec.yaml", "prepare_manifest.json",
                     "execution_plan.json", "mapping.md", "source_trace.json",
                     "draft_receipt.json", "semantic_policy.json",
                     "semantic_receipt.json", "mod_resolution.json"):
            p = self.workdir / name
            if p.is_file():
                texts.append((name, p.read_text(encoding="utf-8")))
        for label, text in texts:
            for token in FORBIDDEN_TOKENS:
                self.assertNotIn(token, text,
                                 f"forbidden token {token!r} in {label}")

    def test_negative_regression_legacy_duplicate_label_ambiguous(self):
        """Same fixture, bad spec: ONLY `source: Capacity` (legacy string,
        field_label_column: B, Capacity ×3) → compile MUST fail with exit 3 and
        MATRIX_FIELD_LOCATOR_AMBIGUOUS; NOT_FOUND must not appear. The CLI is
        the authoritative seam; an in-process compile_spec assertion rides
        along (cheap)."""
        wd = self.workdir
        manifest = self._prepare()
        self._verify_flat_contract(manifest)
        (wd / "mod_resolution.json").write_text(
            json.dumps(mod_record(self.mods), ensure_ascii=False),
            encoding="utf-8")
        spec = build_negative_spec(manifest)
        (wd / "fill_spec_negative.yaml").write_text(
            yaml.safe_dump(spec, allow_unicode=True, sort_keys=False),
            encoding="utf-8")

        # CLI (authoritative)
        proc = run_py(wd, "compile_fill.py", "--spec", "fill_spec_negative.yaml",
                      "--workdir", ".")
        self.assertEqual(proc.returncode, 3,
                         f"expected exit 3, got {proc.returncode}: "
                         f"{proc.stdout} {proc.stderr}")
        self.assertIn("MATRIX_FIELD_LOCATOR_AMBIGUOUS", proc.stderr)
        self.assertNotIn("MATRIX_FIELD_LOCATOR_NOT_FOUND", proc.stderr)
        payload = json.loads(proc.stderr)
        codes = [d["code"] for d in payload["defects"]]
        self.assertIn("MATRIX_FIELD_LOCATOR_AMBIGUOUS", codes)
        self.assertNotIn("MATRIX_FIELD_LOCATOR_NOT_FOUND", codes)
        # first / fully AMBIGUOUS: both sides resolve the duplicated label
        self.assertTrue(all(c == "MATRIX_FIELD_LOCATOR_AMBIGUOUS"
                            for c in codes), codes)
        # a failing compile must not produce a plan
        self.assertFalse((wd / "execution_plan.json").exists())

        # In-process (same compiler entry the CLI uses)
        if str(SCRIPTS) not in sys.path:
            sys.path.insert(0, str(SCRIPTS))
        import compile_fill  # noqa: PLC0415
        from io import StringIO  # noqa: PLC0415
        buf = StringIO()
        old = sys.stderr
        sys.stderr = buf
        try:
            with self.assertRaises(SystemExit) as cm:
                compile_fill.compile_spec(spec, manifest, wd)
            self.assertEqual(cm.exception.code, 3)
        finally:
            sys.stderr = old
        inner = json.loads(buf.getvalue())
        inner_codes = [d["code"] for d in inner["defects"]]
        self.assertIn("MATRIX_FIELD_LOCATOR_AMBIGUOUS", inner_codes)
        self.assertNotIn("MATRIX_FIELD_LOCATOR_NOT_FOUND", inner_codes)


if __name__ == "__main__":
    unittest.main()